config:
  dev_branch_name: dev
  slack_channel: sherlock-ci
  slack_notify: true
deployment_config:
  prod:
    ingress:
      hosts:
      - host: .tiki.services
        paths:
        - path: /
          port: 80
  uat:
    ingress:
      hosts:
      - host: .dev.tiki.services
        paths:
        - path: /
          port: 80
jobs:
  build_docker:
    steps:
    - build_image
  deploy_dev:
    steps:
    - deploy_dev:
        has_worker: 'no'
        namespace: danalytics
        spinnaker_pipeline: generic-v2
        workload: hades
  publish_docker:
    steps:
    - push_image
version: 2
workflows:
  jenkins_pipeline:
    jobs:
    - build_docker
    - publish_docker:
        filters:
          branches:
            only:
            - master
            - dev
            - staging
        requires:
        - build_docker
    - deploy_dev:
        filters:
          branches:
            only:
            - dev
        requires:
        - publish_docker
