version: 1

config:
    slack_notify: true
    slack_channel: 'sherlock-ci'
    dev_branch_name: dev

jobs:
    build_docker:
        steps:
            - build_image

    publish_docker:
        steps:
            - push_image

    deploy_dev:
        steps:
        - deploy_dev:
            workload: 'hades'
            has_worker: "no"
    deploy_production:
        steps:
        - deploy_production:
            workload: 'hades'
            has_worker: "no"

workflows:
    jenkins_pipeline:
        jobs:
            - build_docker
            - publish_docker:
                requires:
                    - build_docker
                filters:
                    branches:
                        only:
                            - master
                            - dev
                            - staging
            - deploy_dev:
                requires:
                    - publish_docker
                filters:
                    branches:
                        only:
                            - dev
